import { readFileSync, existsSync } from "node:fs";
import yaml from "js-yaml";
import type { RenderContext } from "../types.js";

export class EnvSynthesisError extends Error {
  constructor(public reason: string, message: string) {
    super(message);
    this.name = "EnvSynthesisError";
  }
}

interface ToolsYaml {
  mcp_servers?: Array<{ name?: string; env?: Record<string, string> }>;
  required_env?: string[];
  [key: string]: unknown;
}

function parseEnvFile(content: string): Map<string, string> {
  const map = new Map<string, string>();
  for (const rawLine of content.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) continue;
    const eq = line.indexOf("=");
    if (eq === -1) continue;
    const key = line.slice(0, eq).trim();
    let value = line.slice(eq + 1).trim();
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    map.set(key, value);
  }
  return map;
}

export interface EnvSynthesisInputs {
  secretsEnvPath: string;
  toolsYamlPath: string;
}

export function synthesiseEnvFile(ctx: RenderContext, inputs: EnvSynthesisInputs): string {
  if (!existsSync(inputs.secretsEnvPath)) {
    throw new EnvSynthesisError(
      "tenant-not-provisioned",
      `_secrets.env not found at ${inputs.secretsEnvPath}; provision-tenant.sh must run first (Day-4 §6.5).`,
    );
  }
  const secrets = parseEnvFile(readFileSync(inputs.secretsEnvPath, "utf-8"));
  let requiredKeys: string[] = [];
  if (existsSync(inputs.toolsYamlPath)) {
    const tools = yaml.load(readFileSync(inputs.toolsYamlPath, "utf-8")) as ToolsYaml;
    if (Array.isArray(tools?.required_env)) {
      requiredKeys = tools.required_env;
    } else if (Array.isArray(tools?.mcp_servers)) {
      const envKeys = new Set<string>();
      for (const server of tools.mcp_servers) {
        if (server?.env) for (const key of Object.keys(server.env)) envKeys.add(key);
      }
      requiredKeys = [...envKeys];
    }
  }
  const lines: string[] = [
    `# Generated by IFOS agent renderer (packages/agent-renderer/) per ADR-003 §2.1 row 3.`,
    `# Tenant: ${ctx.tenantSlug}    Agent: ${ctx.agentName}`,
    `# Do not edit; regenerate via render-agent.`,
    "",
    `CTX_INSTANCE_ID=${ctx.ctxInstanceId}`,
    `CTX_TENANT_SLUG=${ctx.tenantSlug}`,
    `CTX_AGENT_NAME=${ctx.agentName}`,
    `CTX_AGENT_DIR=${ctx.orgAgentDir}`,
    "",
  ];
  const missing: string[] = [];
  if (requiredKeys.length === 0) {
    for (const [key, value] of secrets.entries()) {
      lines.push(`${key}=${value}`);
    }
  } else {
    for (const key of requiredKeys) {
      const value = secrets.get(key);
      if (value === undefined) {
        missing.push(key);
      } else {
        lines.push(`${key}=${value}`);
      }
    }
  }
  if (missing.length > 0) {
    throw new EnvSynthesisError(
      "bundle-malformed",
      `tools.yaml declares required env keys not present in _secrets.env: ${missing.join(", ")}`,
    );
  }
  return lines.join("\n") + "\n";
}
