import { auth } from '@clerk/nextjs/server';
import { redirect } from 'next/navigation';
import { db } from '@intelforce/db';
import {
  Zap,
  CheckCircle2,
  Clock,
  PoundSterling,
  Bot,
  Activity as ActivityIcon,
  ArrowRight,
} from 'lucide-react';
import {
  PageHeader,
  StatTile,
  Card,
  CardBody,
  StatusPill,
  Eyebrow,
  RelativeTime,
} from '@/components/shared';
import { AgentWeb, type IntegrationGroup } from '@/components/agents/agent-web';

export const metadata = { title: 'Agents' };

// 11 agents across 4 directors. HR slimmed to two: HR Assistant (omnichannel
// Q&A) + Email Handler. Approval routing now done inline by the Assistant;
// weekly reporting moved to Operations / Reporting Engine.
type AgentStatus = 'ACTIVE' | 'RUNNING' | 'SCHEDULED' | 'IDLE';

interface AgentSpec {
  key: string;
  name: string;
  director: 'HR' | 'Sales' | 'Marketing' | 'Operations';
  status: AgentStatus;
  model: 'claude-opus-4-7' | 'claude-sonnet-4-6';
  description: string;
  schedule: string;
  output: string;
  integrations: string[];
}

const DIRECTORS = {
  HR: { color: '#a78bfa', bg: 'rgba(167,139,250,0.12)', tone: 'brand' as const, count: 0 },
  Sales: { color: '#60a5fa', bg: 'rgba(96,165,250,0.12)', tone: 'info' as const, count: 0 },
  Marketing: { color: '#5eead4', bg: 'rgba(94,234,212,0.12)', tone: 'good' as const, count: 0 },
  Operations: { color: '#fdba74', bg: 'rgba(253,186,116,0.12)', tone: 'warn' as const, count: 0 },
};

// Trimmed input set — the 6 connectors that actually drive everyday traffic.
// Anything else (Stripe, Google Drive, Fathom) lives in the Integrations
// settings page; surfacing it on the canvas was just visual noise.
const CHANNELS: IntegrationGroup = {
  label: 'Channels',
  items: [
    { name: 'Microsoft Teams', status: 'live', meta: '4m ago' },
    { name: 'Slack', status: 'live', meta: 'live' },
    { name: 'Gmail', status: 'live', meta: 'live' },
  ],
};

const DATA_SOURCES: IntegrationGroup = {
  label: 'Data sources',
  items: [
    { name: 'Breathe HR', status: 'live' },
    { name: 'HubSpot', status: 'live' },
    { name: 'Notion', status: 'live' },
  ],
};

const TRIGGERS: IntegrationGroup = {
  label: 'Triggers',
  items: [{ name: 'Cron', status: 'live', meta: '2 jobs' }],
};

const AGENTS: AgentSpec[] = [
  // ── HR Director (claude-sonnet-4-6) ─────────────────────────────────────
  // Reworked: one unified assistant handles questions across Teams + Slack +
  // email. Approval routing + weekly reporting kept as distinct concerns.
  {
    key: 'hr-assistant',
    name: 'HR Assistant',
    director: 'HR',
    status: 'ACTIVE',
    model: 'claude-sonnet-4-6',
    description:
      'Answers employee HR questions across Teams, Slack, and email. Combines handbook lookup with live Breathe HR data (leave entitlement, absence history, department mapping). Drafts a reply for HR Lead approval; sensitivity ≥ 0.7 escalates directly without a draft.',
    schedule: 'On-demand',
    output: 'Drafts ready for review',
    integrations: ['Microsoft Teams', 'Slack', 'Email', 'Breathe HR', 'Company handbook'],
  },
  {
    key: 'email-handler',
    name: 'Email Handler',
    director: 'HR',
    status: 'ACTIVE',
    model: 'claude-sonnet-4-6',
    description:
      'Watches the shared HR inbox, classifies incoming threads (policy question, leave request, grievance, payroll), and routes each to the right downstream action. Threads tagged for HR Lead before any reply leaves the inbox.',
    schedule: 'On email',
    output: 'Inbox triaged',
    integrations: ['Email', 'Breathe HR'],
  },
  // Approval Router + Weekly Reporter retired from the HR Director — both
  // were thin abstractions over the HR Assistant's existing capabilities.
  // The Assistant routes drafts via Teams/Slack natively and the weekly
  // report is now generated by the Reporting Engine under Operations.

  // ── Sales Director (claude-opus-4-7) ────────────────────────────────────
  {
    key: 'proposal-builder',
    name: 'Proposal Builder',
    director: 'Sales',
    status: 'RUNNING',
    model: 'claude-opus-4-7',
    description:
      'Pulls discovery call notes from Fathom, references past winning proposals stored in Notion, and drafts a scoped engagement with pricing and timeline. Sent for review the moment a call ends.',
    schedule: 'On call-end',
    output: '£24,200 engagement',
    integrations: ['Fathom', 'HubSpot', 'Notion'],
  },
  {
    key: 'lead-hunter',
    name: 'Lead Hunter',
    director: 'Sales',
    status: 'ACTIVE',
    model: 'claude-opus-4-7',
    description:
      'Queries Companies House and Apollo/Clay, qualifies against the client ICP, and writes enriched lead records to HubSpot. De-duplicates against existing contacts and assigns scores by firmographic fit.',
    schedule: 'Daily 08:00',
    output: '38 qualified leads',
    integrations: ['HubSpot', 'Companies House', 'Clay'],
  },
  {
    key: 'follow-up-pilot',
    name: 'Follow-Up Pilot',
    director: 'Sales',
    status: 'ACTIVE',
    model: 'claude-opus-4-7',
    description:
      'Monitors CRM for dormant prospects (>14 days of inactivity), generates voice-matched follow-ups, and books replies into Calendly. Current run: 21 sends with 7 replies (33% open rate).',
    schedule: 'Hourly',
    output: '21 sends · 7 replies',
    integrations: ['Gmail', 'HubSpot', 'Calendly'],
  },

  // ── Marketing Director (claude-opus-4-7) ────────────────────────────────
  {
    key: 'content-creator',
    name: 'Content Creator',
    director: 'Marketing',
    status: 'RUNNING',
    model: 'claude-opus-4-7',
    description:
      'Trained on the client voice profile (URL samples + tone description from onboarding). Produces long-form content from a one-line brief — blog posts, LinkedIn articles, email sequences. Drafts staged in Notion for review.',
    schedule: 'On-brief',
    output: '4 drafts queued',
    integrations: ['Notion', 'Google Docs'],
  },
  {
    key: 'repurposer',
    name: 'Repurposer',
    director: 'Marketing',
    status: 'ACTIVE',
    model: 'claude-opus-4-7',
    description:
      'Takes one pillar piece (podcast, long-form article, webinar) and turns it into LinkedIn post, Instagram carousel, YouTube Short script, email, and X thread — all voice-matched and ready for Buffer.',
    schedule: 'On pillar publish',
    output: '9 derivative pieces',
    integrations: ['Notion', 'Buffer'],
  },
  {
    key: 'caption-writer',
    name: 'Caption Writer',
    director: 'Marketing',
    status: 'ACTIVE',
    model: 'claude-opus-4-7',
    description:
      'Writes platform-native social captions with CTAs tuned per network. Sources assets from Drive, writes captions in client tone, queues them in Buffer with optimal timing based on historical engagement.',
    schedule: 'Daily 07:00',
    output: '17 captions ready',
    integrations: ['Buffer', 'Google Drive'],
  },

  // ── Operations Director (claude-sonnet-4-6) ─────────────────────────────
  {
    key: 'client-onboarder',
    name: 'Client Onboarder',
    director: 'Operations',
    status: 'ACTIVE',
    model: 'claude-sonnet-4-6',
    description:
      'Fires on contract signature via DocuSign webhook. Creates the Slack channel, sends the welcome sequence, dispatches the intake form, and drops the kickoff invite in the client calendar.',
    schedule: 'On contract sign',
    output: '2 in progress',
    integrations: ['DocuSign', 'Slack', 'ClickUp'],
  },
  {
    key: 'reporting-engine',
    name: 'Reporting Engine',
    director: 'Operations',
    status: 'SCHEDULED',
    model: 'claude-sonnet-4-6',
    description:
      'Aggregates Stripe revenue, GA4 traffic, Meta Ads performance, and CRM pipeline. Delivers a weekly intelligence briefing to Slack and as a PDF — ready before Monday standup.',
    schedule: 'Friday 07:00',
    output: 'Weekly briefing',
    integrations: ['Stripe', 'GA4', 'Meta Ads', 'Slack'],
  },
  {
    key: 'sop-writer',
    name: 'SOP Writer',
    director: 'Operations',
    status: 'IDLE',
    model: 'claude-sonnet-4-6',
    description:
      'Ingests Loom screen recordings and auto-generates Notion-formatted SOPs from the narration and screen actions. Library has 34 SOPs. Idle — no new Looms queued.',
    schedule: 'On Loom upload',
    output: '34 SOPs in library',
    integrations: ['Loom', 'Notion'],
  },
];

const STATUS_TONE: Record<AgentStatus, 'good' | 'warn' | 'info' | 'muted'> = {
  ACTIVE: 'good',
  RUNNING: 'warn',
  SCHEDULED: 'info',
  IDLE: 'muted',
};

const STATUS_DOT: Record<AgentStatus, string> = {
  ACTIVE: 'bg-emerald-400',
  RUNNING: 'bg-amber-400',
  SCHEDULED: 'bg-sky-400',
  IDLE: 'bg-zinc-500',
};

export default async function AgentsPage({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { userId } = await auth();
  if (!userId) redirect('/sign-in');

  const { slug } = await params;
  const tenant = await db.tenant.findUnique({
    where: { slug },
    select: { id: true, name: true },
  });
  if (!tenant) return null;

  const since = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000);
  const [agentStats, totalInvocations, openEscalations, costAgg, weeklyAgg] = await Promise.all([
    db.invocation.groupBy({
      by: ['agent'],
      where: { tenantId: tenant.id },
      _count: { _all: true },
      _max: { startedAt: true },
      _sum: { costGbp: true },
      _avg: { durationMs: true },
    }),
    db.invocation.count({ where: { tenantId: tenant.id } }),
    db.escalation.count({ where: { tenantId: tenant.id, status: 'OPEN' } }),
    db.cost.aggregate({
      where: { tenantId: tenant.id },
      _sum: { costGbp: true },
    }),
    db.invocation.aggregate({
      where: { tenantId: tenant.id, startedAt: { gte: since } },
      _count: { _all: true },
      _avg: { durationMs: true },
    }),
  ]);

  function findStat(spec: AgentSpec) {
    const target = spec.name.toLowerCase().replace(/\s+/g, '-');
    return agentStats.find((s) => {
      const a = (s.agent || '').toLowerCase();
      return a === target || a === spec.key || a.includes(spec.key);
    });
  }

  const activeCount = AGENTS.filter((a) => a.status === 'ACTIVE' || a.status === 'RUNNING').length;
  const totalCost = Number(costAgg._sum.costGbp ?? 0);
  const weeklyCount = weeklyAgg._count._all ?? 0;
  const avgDurationMs = weeklyAgg._avg.durationMs ?? null;
  const avgCostPerInv = totalInvocations > 0 ? totalCost / totalInvocations : 0;

  const directorCounts = AGENTS.reduce(
    (acc, a) => {
      acc[a.director] = (acc[a.director] || 0) + 1;
      return acc;
    },
    {} as Record<string, number>,
  );

  return (
    <div className="space-y-6">
      <PageHeader
        title="Agents"
        description={`${AGENTS.length} sub-agents across 4 directors — running on claude-opus-4.7 + sonnet-4.6, working together to handle the daily grind. Every draft requires HR Lead approval at the gate.`}
        actions={
          <div className="flex items-center gap-3 text-xs text-text-muted">
            <span className="flex items-center gap-1.5">
              <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 pulse-dot" />
              Active
            </span>
            <span className="flex items-center gap-1.5">
              <span className="w-1.5 h-1.5 rounded-full bg-amber-400 pulse-dot" />
              Running
            </span>
            <span className="flex items-center gap-1.5">
              <span className="w-1.5 h-1.5 rounded-full bg-sky-400" />
              Scheduled
            </span>
            <span className="flex items-center gap-1.5">
              <span className="w-1.5 h-1.5 rounded-full bg-zinc-500" />
              Idle
            </span>
          </div>
        }
      />

      {/* KPI strip */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-3 sm:gap-4">
        <StatTile
          label="Agents active"
          value={`${activeCount} of ${AGENTS.length}`}
          hint={`${openEscalations} pending HR Lead review`}
          icon={Bot}
          tone={openEscalations > 0 ? 'warn' : 'good'}
        />
        <StatTile
          label="Invocations · 7d"
          value={weeklyCount.toLocaleString()}
          hint={`${totalInvocations.toLocaleString()} all-time`}
          icon={ActivityIcon}
          tone="neutral"
        />
        <StatTile
          label="Avg latency"
          value={avgDurationMs ? `${Math.round(avgDurationMs)}ms` : '—'}
          hint={avgDurationMs && avgDurationMs > 3000 ? 'Slower than target' : 'Within p50 target'}
          icon={Clock}
          tone={avgDurationMs && avgDurationMs > 3000 ? 'warn' : 'good'}
        />
        <StatTile
          label="Cost / invocation"
          value={avgCostPerInv > 0 ? `£${avgCostPerInv.toFixed(4)}` : '—'}
          hint={`£${totalCost.toFixed(2)} all-time`}
          icon={PoundSterling}
          tone="neutral"
        />
      </div>

      {/* Multi-agent web — channels → gateway → directors → sub-agents.
          `slug` is what flips the canvas into live mode (polling
          /api/agents/[slug]/activity every 10s for the stream + sparklines). */}
      <AgentWeb
        agents={AGENTS}
        channels={CHANNELS}
        dataSources={DATA_SOURCES}
        triggers={TRIGGERS}
        slug={slug}
      />

      {/* Compact per-agent activity — single table replaces the 4 director
          sections. Description + integrations are surfaced in the inline detail
          panel of AgentWeb on click; this table is the at-a-glance numbers. */}
      <Card data-agent-activity-table>
        <CardBody className="p-0">
          <div className="px-5 py-3 border-b border-white/5 flex items-center justify-between">
            <div>
              <p className="text-[10px] tracking-widest uppercase text-text-muted font-medium">
                Per-agent activity
              </p>
              <p className="text-xs text-text-secondary mt-0.5">
                Click any agent in the web above for description + integrations.
              </p>
            </div>
            <span className="text-[10px] font-mono text-text-muted">
              {AGENTS.length} agents · sorted by runs
            </span>
          </div>
          <div className="divide-y divide-white/[0.04]">
            {[...AGENTS]
              .map((spec) => ({ spec, stats: findStat(spec) }))
              .sort((a, b) => (b.stats?._count._all ?? 0) - (a.stats?._count._all ?? 0))
              .map(({ spec, stats }) => {
                const meta = DIRECTORS[spec.director];
                const count = stats?._count._all ?? 0;
                const lastRun = stats?._max.startedAt;
                const cost = Number(stats?._sum.costGbp ?? 0);
                return (
                  <div
                    key={spec.key}
                    className="px-5 py-2.5 flex items-center gap-3 hover:bg-white/[0.02] transition-colors"
                  >
                    <span
                      className="w-1.5 h-7 rounded-full shrink-0"
                      style={{ background: meta.color }}
                    />
                    <Bot className="w-3.5 h-3.5 shrink-0" style={{ color: meta.color }} />
                    <div className="min-w-0 flex-1">
                      <p className="text-sm font-medium text-text-primary truncate">
                        {spec.name}
                      </p>
                      <p className="text-[10px] text-text-muted font-mono truncate">
                        {spec.director} · {spec.model} · {spec.schedule}
                      </p>
                    </div>
                    <StatusPill
                      tone={STATUS_TONE[spec.status]}
                      showDot
                      pulse={spec.status === 'ACTIVE' || spec.status === 'RUNNING'}
                    >
                      {spec.status}
                    </StatusPill>
                    <div className="hidden sm:grid grid-cols-3 gap-4 text-right shrink-0 w-44">
                      <div>
                        <p className="text-[9px] uppercase tracking-wider text-text-muted">
                          Runs
                        </p>
                        <p className="text-xs font-mono font-semibold text-text-primary">
                          {count.toLocaleString()}
                        </p>
                      </div>
                      <div>
                        <p className="text-[9px] uppercase tracking-wider text-text-muted">
                          Cost
                        </p>
                        <p className="text-xs font-mono font-semibold text-text-primary">
                          £{cost.toFixed(2)}
                        </p>
                      </div>
                      <div>
                        <p className="text-[9px] uppercase tracking-wider text-text-muted">
                          Last
                        </p>
                        <p className="text-xs">
                          {lastRun ? (
                            <RelativeTime date={lastRun} className="text-text-primary text-xs" />
                          ) : (
                            <span className="text-text-muted italic">—</span>
                          )}
                        </p>
                      </div>
                    </div>
                  </div>
                );
              })}
          </div>
        </CardBody>
      </Card>

      {/* Hide the old per-director cards — kept here as a no-render branch in
          case we want to bring back richer cards later. */}
      {false && (Object.keys(DIRECTORS) as Array<keyof typeof DIRECTORS>).map((dir) => {
        const meta = DIRECTORS[dir];
        const agentsForDir = AGENTS.filter((a) => a.director === dir);
        return (
          <div key={dir}>
            <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-3 sm:gap-4">
              {agentsForDir.map((spec) => {
                const stats = findStat(spec);
                const count = stats?._count._all ?? 0;
                const lastRun = stats?._max.startedAt;
                const cost = Number(stats?._sum.costGbp ?? 0);
                return (
                  <Card key={spec.key} variant="interactive">
                    <div
                      className="px-5 py-4 border-b border-white/5 flex items-center gap-3 border-l-2"
                      style={{ borderLeftColor: meta.color }}
                    >
                      <Bot className="w-4 h-4 shrink-0" style={{ color: meta.color }} />
                      <div className="flex-1 min-w-0">
                        <h3 className="text-sm font-semibold text-text-primary truncate">
                          {spec.name}
                        </h3>
                        <p className="text-[11px] text-text-muted truncate">{spec.schedule}</p>
                      </div>
                      <StatusPill tone={STATUS_TONE[spec.status]} showDot pulse={spec.status === 'ACTIVE' || spec.status === 'RUNNING'}>
                        {spec.status}
                      </StatusPill>
                    </div>
                    <CardBody>
                      <p className="text-xs text-text-secondary leading-relaxed mb-4 line-clamp-3">
                        {spec.description}
                      </p>
                      <div className="grid grid-cols-3 gap-2 mb-4">
                        <div>
                          <Eyebrow className="mb-1 text-[9px]">Runs</Eyebrow>
                          <p className="text-sm font-mono font-semibold text-text-primary">
                            {count.toLocaleString()}
                          </p>
                        </div>
                        <div>
                          <Eyebrow className="mb-1 text-[9px]">Cost</Eyebrow>
                          <p className="text-sm font-mono font-semibold text-text-primary">
                            £{cost.toFixed(2)}
                          </p>
                        </div>
                        <div>
                          <Eyebrow className="mb-1 text-[9px]">Last run</Eyebrow>
                          <p className="text-xs text-text-primary">
                            {lastRun ? (
                              <RelativeTime
                                date={lastRun}
                                className="text-text-primary text-xs"
                              />
                            ) : (
                              spec.output && (
                                <span className="text-text-muted text-xs italic">
                                  {spec.output}
                                </span>
                              )
                            )}
                          </p>
                        </div>
                      </div>
                      <div className="space-y-2 mb-3">
                        <Eyebrow className="text-[9px]">Model</Eyebrow>
                        <code className="text-[11px] font-mono" style={{ color: meta.color }}>
                          {spec.model}
                        </code>
                      </div>
                      <div>
                        <Eyebrow className="text-[9px] mb-1.5">Integrations</Eyebrow>
                        <div className="flex flex-wrap gap-1.5">
                          {spec.integrations.map((i) => (
                            <span
                              key={i}
                              className="text-[10px] font-mono px-1.5 py-0.5 rounded bg-white/5 text-text-secondary"
                            >
                              {i}
                            </span>
                          ))}
                        </div>
                      </div>
                    </CardBody>
                  </Card>
                );
              })}
            </div>
          </div>
        );
      })}

      {/* Footer info */}
      <Card>
        <CardBody className="flex flex-wrap items-center gap-x-6 gap-y-2 py-4">
          <div className="flex items-center gap-2 text-sm">
            <Zap className="w-4 h-4 text-emerald-400" />
            <span className="text-text-secondary">
              All agents run on Cloudflare Workers · edge runtime · &lt;100ms p50 cold start
            </span>
          </div>
          <div className="flex items-center gap-2 text-sm">
            <CheckCircle2 className="w-4 h-4 text-emerald-400" />
            <span className="text-text-secondary">
              Every draft requires HR Lead approval — nothing sends without you
            </span>
          </div>
          <a
            href={`/t/${slug}/activity`}
            className="text-xs text-emerald-400 hover:text-emerald-300 flex items-center gap-1 ml-auto"
          >
            View invocations <ArrowRight className="w-3 h-3" />
          </a>
        </CardBody>
      </Card>
    </div>
  );
}
